/*
 *    version.hpp:
 *
 *    Copyright (C) 2023 Light Lin <lxrite@gmail.com> All Rights Reserved.
 *
 */

 
#ifndef AZURE_VERSION_HPP
#define AZURE_VERSION_HPP

#define AHP_MAJOR_VERSION 1
#define AHP_MINOR_VERSION 1
#define AHP_PATCH_VERSION 0

#define AHP_VERSION_TO_STR_(x) #x
#define AHP_VERSION_TO_STR(x) AHP_VERSION_TO_STR_(x)
#define AHP_VERSION_DOT AHP_VERSION_TO_STR_(.)

#if AHP_PATCH_VERSION > 0
#define AHP_VERSION_STRING AHP_VERSION_TO_STR(AHP_MAJOR_VERSION) AHP_VERSION_DOT AHP_VERSION_TO_STR(AHP_MINOR_VERSION) AHP_VERSION_DOT AHP_VERSION_TO_STR(AHP_PATCH_VERSION)
#else
#define AHP_VERSION_STRING AHP_VERSION_TO_STR(AHP_MAJOR_VERSION) AHP_VERSION_DOT AHP_VERSION_TO_STR(AHP_MINOR_VERSION)
#endif

#endif // AZURE_VERSION_HPP
